#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright the OpenAmpere contributors
# SPDX-License-Identifier: MIT
"""Generate THIRD_PARTY_LICENSES.md from the installed runtime dependencies.

Covers everything OpenAmpere ships:
  - Python packages required at runtime (dependency tree of "openampere", without dev extras)
  - npm packages bundled into the web app (production dependency tree of web/), incl. the DM Sans font

Usage (from the repository root, with the dev environment installed and `npm install` done in web/):
    .venv/bin/python scripts/third_party_licenses.py          # write the files
    .venv/bin/python scripts/third_party_licenses.py --check  # fail if they are out of date
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from importlib.metadata import distribution
from pathlib import Path

from packaging.requirements import Requirement

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "THIRD_PARTY_LICENSES.md"
WEB_JSON = ROOT / "web" / "public" / "third-party-licenses.json"  # shown on the in-app licenses page
LICENSE_NAMES = ("LICENSE", "LICENCE", "COPYING", "NOTICE", "AUTHORS")


def python_packages() -> list[dict]:
    seen: dict[str, object] = {}

    def walk(name: str) -> None:
        dist = distribution(name)
        key = dist.metadata["Name"].lower()
        if key in seen:
            return
        seen[key] = dist
        for raw in dist.requires or []:
            req = Requirement(raw)
            if req.marker and not req.marker.evaluate({"extra": ""}):
                continue
            walk(req.name)

    walk("openampere")
    seen.pop("openampere", None)
    packages = []
    for dist in seen.values():
        meta = dist.metadata
        license_name = meta.get("License-Expression") or ""
        if not license_name:
            classifiers = [c.split("::")[-1].strip() for c in meta.get_all("Classifier") or [] if c.startswith("License")]
            license_name = ", ".join(classifiers) or (meta.get("License") or "").splitlines()[0][:60]
        texts = []
        for file in sorted(dist.files or [], key=str):
            if any(part in Path(str(file)).name.upper() for part in LICENSE_NAMES):
                texts.append(dist.locate_file(file).read_text(encoding="utf-8", errors="replace").strip())
        packages.append({"name": meta["Name"], "version": dist.version, "license": license_name,
                         "url": meta.get("Home-page") or _project_url(meta), "texts": texts})
    return sorted(packages, key=lambda p: p["name"].lower())


def _project_url(meta) -> str:
    for entry in meta.get_all("Project-URL") or []:
        label, _, url = entry.partition(",")
        if label.strip().lower() in ("homepage", "source", "repository", "source code"):
            return url.strip()
    return ""


def npm_packages() -> list[dict]:
    web = ROOT / "web"
    tree = json.loads(subprocess.run(["npm", "ls", "--omit=dev", "--all", "--json", "--long"], cwd=web,
                                     capture_output=True, text=True, check=True).stdout)
    found: dict[str, dict] = {}

    def walk(deps: dict) -> None:
        for name, info in (deps or {}).items():
            path = Path(info.get("path", web / "node_modules" / name))
            key = f"{name}@{info.get('version')}"
            if key not in found and path.is_dir():
                manifest = json.loads((path / "package.json").read_text(encoding="utf-8"))
                texts = [f.read_text(encoding="utf-8", errors="replace").strip() for f in sorted(path.iterdir())
                         if f.is_file() and any(part in f.name.upper() for part in LICENSE_NAMES)]
                repo = manifest.get("repository")
                url = repo.get("url", "") if isinstance(repo, dict) else (repo or manifest.get("homepage", ""))
                found[key] = {"name": name, "version": manifest.get("version", ""), "url": url,
                              "license": manifest.get("license", ""), "texts": texts}
            walk(info.get("dependencies"))

    walk(tree.get("dependencies"))
    return sorted(found.values(), key=lambda p: p["name"].lower())


def render(python: list[dict], npm: list[dict]) -> str:
    out = [
        "# Third-party licenses",
        "",
        "OpenAmpere itself is licensed under the MIT License (see LICENSE).",
        "It ships with the following third-party software. Their license texts follow below.",
        "",
        "This file is generated by `scripts/third_party_licenses.py`. Do not edit by hand.",
        "",
    ]
    for title, packages in (("Python packages (backend)", python), ("Web app (bundled into the browser app)", npm)):
        out += [f"## {title}", "", "| Package | Version | License |", "|---|---|---|"]
        out += [f"| {p['name']} | {p['version']} | {p['license'] or 'see text'} |" for p in packages]
        out.append("")
    out += ["---", ""]
    for packages in (python, npm):
        for p in packages:
            out += [f"## {p['name']} {p['version']}", ""]
            out += [f"License: {p['license'] or 'see text'}"] + ([f"Source: {p['url']}"] if p["url"] else []) + [""]
            if p["texts"]:
                for text in p["texts"]:
                    out += ["```", text, "```", ""]
            else:
                out += ["(No license file shipped with the package; license as declared above.)", ""]
    return "\n".join(out).rstrip() + "\n"


def render_json(python: list[dict], npm: list[dict]) -> str:
    own = {"name": "OpenAmpere", "license": "MIT", "texts": [(ROOT / "LICENSE").read_text(encoding="utf-8").strip()]}
    groups = [{"title": "App im Browser", "packages": npm}, {"title": "Server", "packages": python}]
    return json.dumps({"self": own, "groups": groups}, ensure_ascii=False, indent=1) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 if the generated files are outdated")
    args = parser.parse_args()
    python, npm = python_packages(), npm_packages()
    outputs = {OUTPUT: render(python, npm), WEB_JSON: render_json(python, npm)}
    if args.check:
        stale = [p for p, c in outputs.items() if not p.exists() or p.read_text(encoding="utf-8") != c]
        if stale:
            sys.exit(f"out of date: {', '.join(str(p.relative_to(ROOT)) for p in stale)} - run scripts/third_party_licenses.py")
        print("third-party licenses up to date")
        return
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
